spring:
  application:
    name: lab

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
      CheckinCore:
        connectTimeout: 200
        readTimeout: 200
        url: ${integration.checkin-core.url}

integration:
  checkin-core:
    url: ${CHECKIN_CORE_URL:http://localhost:8080}