version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:3.13.2 # Use the official image
    container_name: my_wiremock
    ports:
      - "9001:8080" # Map host port 8080 to container port 8080
    volumes:
      # Mount local directories to the container's working directories
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379" # Map host port 6379 to container port 6379